# Generated by Django 6.0.3 on 2026-09-12 21:31

import conta_cliente.models
import conta_logista.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(unique=True, validators=[conta_cliente.models.validacao_cpf])),
                ('cnae', models.CharField(unique=True)),
                ('cnpj', models.CharField(unique=True, validators=[conta_logista.models.validacao_cnpj])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
