# Generated by Django 6.0.3 on 2026-09-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta_logista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='lojas/logo/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='lojas/banner/')),
                ('categoria', models.CharField(choices=[('r.l', 'Restaurantes e Lanchonetes'), ('mercados', 'Mercados'), ('r.c.a', 'Roupas, Calçados e Acessórios'), ('f.c', 'Ferramentas e Construção')], max_length=50)),
                ('logista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta_logista.logista')),
            ],
        ),
    ]
