# Generated by Django 6.0.3 on 2026-09-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='categoria',
            field=models.CharField(choices=[('r.l', 'Restaurantes e Lanchonetes'), ('mercados', 'Mercados'), ('r.c.a', 'Roupas, Calçados e Acessórios'), ('f.c', 'Ferramentas e Construção'), ('m.b', 'Moda e Beleza'), ('pet-shop', 'Pet-shop'), ('saude', 'Saúde'), ('m.g', 'Músicas e Games')], max_length=50),
        ),
    ]
