# Generated by Django 6.0.3 on 2026-09-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta_logista', '0001_initial'),
        ('loja', '0002_alter_loja_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='logista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conta_logista.logista'),
        ),
    ]
